{
  name: 'dsbn_adapt',
  prior: 'logistic',
  learning_rate: 0.0001,
  dim_h: 200,
  n_layers: 2,
  epochs: 500,
  batch_size: 100,
  valid_batch_size: 10,
  max_valid: 1000,
  center_latent: True,
  optimizer: 'adam',
  recognition_net: {
    dim_h: 250,
    h_act: 'T.nnet.softplus',
    n_layers: 2,
    weight_scale: 0.001
  },
  generation_net: {
    dim_h: 250,
    h_act: 'T.nnet.softplus',
    n_layers: 2,
    weight_scale: 0.001
  },
  z_init: 'recognition_net',
  inference_method: 'adaptive',
  inference_rate: 0.02,
  n_inference_steps: 20,
  n_inference_steps_test: 20,
  n_inference_samples: 20,
  inference_decay: 1.0,
  n_mcmc_samples: 20,
  n_mcmc_samples_test: 20,
  dataset: 'mnist',
  dataset_args: {
    source: '/Users/devon/Data/mnist_binarized_salakhutdinov.pkl.gz'
  }
}