{
  name: 'dsbn_adapt',
  prior: 'logistic',
  learning_rate: 0.0001,
  dim_h: 200,
  n_layers: 2,
  epochs: 500,
  batch_size: 100,
  optimizer: 'rmsprop',
  recognition_net: {
    dim_h: 250,
    h_act: 'T.nnet.softplus',
    n_layers: 1,
  },
  generation_net: {
    dim_h: 250,
    h_act: 'T.nnet.softplus',
    n_layers: 1,
  },
  z_init: 'recognition_net',
  inference_method: 'adaptive',
  inference_rate: 0.1,
  n_inference_steps: 50,
  n_inference_steps_test: 50,
  n_inference_samples: 20,
  n_mcmc_samples: 20,
  n_mcmc_samples_test: 20,
  dataset: 'mnist',
  dataset_args: {
    source: '/export/mialab/users/dhjelm/data/mnist_binarized_salakhutdinov.pkl.gz',
  },
  show_freq: 1000,
  model_save_freq: 1000,
}