{
  name: 'dsbn',
  prior: 'logistic',
  learning_rate: 0.0001,
  dim_h: 200,
  n_layers: 2,
  epochs: 500,
  batch_size: 10,
  valid_batch_size: 10,
  max_valid: 1000,
  optimizer: 'adam',
  recognition_net: {
    dim_h: 200,
    h_act: 'T.nnet.softplus',
    n_layers: 2
  },
  generation_net: {
    dim_h: 200,
    h_act: 'T.nnet.softplus',
    n_layers: 2
  },
  z_init: 'recognition_net',
  inference_method: 'momentum',
  inference_rate: 0.001,
  n_inference_steps: 20,
  n_inference_steps_test: 20,
  n_inference_samples: 20,
  n_mcmc_samples: 20,
  n_mcmc_samples_test: 20,
  dataset: 'mnist',
  dataset_args: {
    source: '/export/mialab/users/dhjelm/data/mnist_binarized_salakhutdinov.pkl.gz'
  }
}