{
  name: 'ct_darn_air_200',
  prior: 'darn',
  learning_rate: 0.0001,
  dim_h: 200,
  epochs: 500,
  batch_size: 100,
  l2_decay: 0.002,
  optimizer: 'rmsprop',
  recognition_net: {
    input_layer: 'caltech',
    dim_h: 500,
    h_act: 'T.tanh',
    n_layers: 1,
  },
  generation_net: {
    dim_h: 500,
    h_act: 'T.tanh',
    n_layers: 2,
    output: 'caltech',
  },
  z_init: 'recognition_net',
  inference_method: 'adaptive',
  inference_rate: 0.1,
  n_inference_steps: 20,
  n_inference_steps_test: 100,
  n_inference_samples: 20,
  n_inference_samples_test: 100,
  n_mcmc_samples: 20,
  n_mcmc_samples_test: 1000,
  dataset: 'caltech',
  dataset_args: {
    source: '/export/mialab/users/dhjelm/data/caltech101_silhouettes_28_split1.mat',
  },
  show_freq: 1000,
  model_save_freq: 1000,
}