{
  name: 'mnist1000d_9',
  batch_size: 10,
  dim_h: 1000,
  optimizer: 'adam',
  mode: 'gru',
  learning_rate: 0.01,
  steps: 500000,
  h_init: 'noise',
  metric: 'euclidean_then_energy',
  noise_input: True,
  i_net: {
    dim_h: 1000,
    n_layers: 2,
    h_act: 'T.tanh',
    out_act: 'T.tanh',
    weight_scale: 0.1,
  },
  a_net: {
    dim_h: 1000,
    n_layers: 2,
    h_act: 'T.tanh',
    h_act: 'T.tanh',
    weight_scale: 0.1
  },
  o_net: {
    dim_h: 1000,
    n_layers: 2,
    weight_scale: 0.1
  },
  dataset_args: {
    source: '/Users/devon/Data/mnist.pkl.gz',
    window: 20,
    chain_build_batch: 100,
    chain_length: 500,
    chain_stride: 3,
    stop: 5000,
    trim_end: 5
  }, 
  dataset: 'mnist'
}