{
  name: 'mnist_rbm_200_1',
  batch_size: 10,
  dim_h: 200,
  optimizer: 'adam',
  learning_rate: 0.01,
  steps: 500000,
  metric: 'euclidean_then_energy',
  noise_input: False,
  dataset_args: {    
    source: '/Users/devon/Data/mnist.pkl.gz',
    window: 20,
    chain_build_batch: 2000,
    chain_length: 2000,
    chain_stride: 3
  }, 
  dataset: 'mnist'
}