{
  name: 'mnist_rnn_200d_2',
  batch_size: 10,
  dim_h: 200,
  optimizer: 'adam',
  mode: 'rnn',
  learning_rate: 0.01,
  steps: 500000,
  metric: 'euclidean_then_energy',
  noise_input: False,
  mlp_b: {
    dim_h: 200,
    n_layers: 2,
    h_act: 'T.tanh',
    weight_scale: 0.1
  },
  mlp_o: {
    dim_h: 200,
    n_layers: 2,
    weight_scale: 0.1
  },
  dataset_args: {    
    source: '/Users/devon/Data/mnist.pkl.gz',
    window: 20,
    chain_build_batch: 2000,
    chain_length: 2000,
    chain_stride: 3
  }, 
  dataset: 'mnist'
}