{
  name: 'sbn_simple',
  prior: 'logistic',
  learning_rate: 0.003,
  dim_h: 201,
  recognition_net: {
    dim_h: 200,
    h_act: 'T.nnet.softplus',
    n_layers: 1
  },
  generation_net: {
    dim_h: 200,
    h_act: 'T.nnet.softplus',
    n_layers: 1
  },
  z_init: 'recognition_net',
  inference_method: 'momentum_2',
  inference_rate: .003,
  n_inference_steps: 0,
  n_inference_steps_test: 0,
  inference_decay: 1.0,
  n_mcmc_samples: 20,
  n_mcmc_samples_test: 20,
  dataset: 'mnist',
  dataset_args: {
    source: '/Users/devon/Data/mnist_binarized_salakhutdinov.pkl.gz'
  }
}