{
  name: 'sbn_cont',
  prior: 'logistic',
  learning_rate: 0.03,
  dim_h: 200,
  recognition_net: {
    dim_h: 200,
    h_act: 'T.nnet.softplus',
    n_layers: 2
  },
  generation_net: {
    dim_h: 200,
    h_act: 'T.nnet.softplus',
    n_layers: 2
  },
  z_init: 'recognition_net',
  inference_method: 'momentum',
  inference_rate: .003,
  n_inference_steps: 20,
  n_inference_steps_test: 20,
  n_inference_samples: 20,
  inference_scaling: 'continuous',
  inference_decay: 1.0,
  n_mcmc_samples: 20,
  n_mcmc_samples_test: 20,
  alpha: 10,
  dataset: 'mnist',
  dataset_args: {
    source: '/export/mialab/users/dhjelm/data/mnist_binarized_salakhutdinov.pkl.gz'
  }
}