{
  name: 'momentum_12',
  batch_size: 100,
  dim_h: 200,
  n_layers: 3,
  learning_rate: 0.1,
  lr_decay: False,
  inference_samples: 20,
  inference_procedure: {
    method: 'momentum',
    n_inference_steps: 100,
    decay: 1.0,
    momentum: 0.9,
    inference_rates: [0.1, 0.1]
  },
  optimizer: 'adam',
  source: '/Users/devon/Data/mnist.pkl.gz',
  dataset: 'mnist',
  weight_scale: 0.1,
}