{
  name: 'darn_air50_500',
  prior: 'darn',
  dim_h: 500,
  learning_args: {
    epochs: 500,
    n_posterior_samples: 20,
    n_posterior_samples_test: 100,
    batch_size: 100,
    learning_rate: 0.0001,
    optimizer: 'rmsprop',
    epochs: 500,
    l2_decay: 0.0002
  },
  recognition_net: {
    input_layer: 'mnist',
    dim_hs: [],
    h_act: 'T.tanh',
  },
  generation_net: {
    dim_hs: [500],
    h_act: 'T.tanh',
    output: 'mnist',
  },
  inference_args: {
    inference_method: 'air',
    inference_rate: 0.1,
    n_inference_steps: 50,
    n_inference_samples: 50,
  },
  inference_args_test: {
    inference_method: 'air',
    inference_rate: 0.1,
    n_inference_steps: 50,
    n_inference_samples: 50,
  },
  dataset_args: {
    dataset: 'mnist',
    source: '$irvi_data/mnist_binarized_salakhutdinov.pkl.gz',
  }
}