{
  name: 'sbn_air_2rec_200',
  prior: 'logistic',
  learning_rate: 0.0001,
  dim_h: 200,
  epochs: 500,
  batch_size: 100,
  l2_decay: 0.0002,
  optimizer: 'rmsprop',
  recognition_net: {
    input_layer: 'mnist',
    dim_h: 240,
    h_act: 'T.nnet.softplus',
    n_layers: 2
  },
  generation_net: {
    dim_h: 240,
    h_act: 'T.nnet.softplus',
    n_layers: 1,
    output: 'mnist'
  },
  z_init: 'recognition_net',
  inference_method: 'adaptive',
  inference_rate: 0.1,
  n_inference_steps: 20,
  n_inference_steps_test: 20,
  n_inference_samples: 20,
  n_inference_samples_test: 20,
  n_mcmc_samples: 20,
  n_mcmc_samples_test: 100,
  dataset: 'mnist',
  dataset_args: {
    source: '/export/mialab/users/dhjelm/data/mnist_binarized_salakhutdinov.pkl.gz',
  },
  show_freq: 1000,
  model_save_freq: 1000
}