{
  name: 'sbn_air_big',
  prior: 'binomial',
  dim_hs: [400, 300, 200, 100, 10],
  learning_args: {
    epochs: 500,
    n_posterior_samples: 20,
    n_posterior_samples_test: 100,
    batch_size: 100,
    learning_rate: 0.0001,
    optimizer: 'rmsprop',
    epochs: 500,
    l2_decay: 0.0002
  },
  inference_args: {
    inference_method: 'air',
    inference_rate: 0.01,
    n_inference_steps: 100,
    n_inference_samples: 100,
  },
  inference_args_test: {
    inference_method: 'air',
    inference_rate: 0.01,
    n_inference_steps: 100,
    n_inference_samples: 100,
  },
  dataset_args: {
    dataset: 'mnist',
    source: '$irvi_data/mnist_binarized_salakhutdinov.pkl.gz',
  }
}