{
  name: 'sbn_air_200',
  prior: 'binomial',
  dim_h: 200,
  learning_args: {
    epochs: 500,
    n_posterior_samples: 20,
    n_posterior_samples_test: 100,
    batch_size: 100,
    learning_rate: 0.0001,
    optimizer: 'rmsprop',
    epochs: 500,
    l2_decay: 0.0002
  },
  inference_args: {
    inference_method: 'air',
    inference_rate: 0.1,
    n_inference_steps: 20,
    n_inference_samples: 20,
  },
  inference_args_test: {
    inference_method: 'air',
    inference_rate: 0.1,
    n_inference_steps: 20,
    n_inference_samples: 20,
  },
  dataset_args: {
    dataset: 'mnist',
    source: '$irvi_data/mnist_binarized_salakhutdinov.pkl.gz',
  }
}