{
  name: 'sbn_simple',
  prior: 'logistic',
  learning_rate: 0.03,
  dim_h: 200,
  epochs: 500,
  batch_size: 10,
  valid_batch_size: 10,
  max_valid: 1000,
  center_latent: True,
  optimizer: 'rmsprop',
  optimizer_args: {
    relaxation: 0.003,
    momentum: 0.97,
    coefficient: 0.978,
  },
  recognition_net: {
    dim_h: 250,
    h_act: 'T.nnet.softplus',
    n_layers: 2
  },
  generation_net: {
    dim_h: 250,
    h_act: 'T.nnet.softplus',
    n_layers: 2
  },
  z_init: 'recognition_net',
  inference_method: 'momentum',
  inference_rate: 1.0,
  n_inference_steps: 0,
  n_inference_steps_test: 0,
  n_inference_samples: 20,
  inference_decay: 1.0,
  n_mcmc_samples: 20,
  n_mcmc_samples_test: 20,
  dataset: 'mnist',
  dataset_args: {
    source: '/Users/devon/Data/mnist_binarized_salakhutdinov.pkl.gz'
  }
}